---
gluster_create_volume: false
gluster_device: "/dev/vdb"
gluster_vg_name: "vg_gluster"
gluster_lv_name: "brick1"
gluster_root_folder: "/bricks"
gluster_volume_name: "glustervol1"
gluster_volume_folder: "brick1"
gluster_volume_size: "5G"
gluster_server1: "k8s-gluster1.prototype.local"
gluster_server2: "k8s-gluster2.prototype.local"
gluster_server3: "k8s-gluster3.prototype.local"
gluster_server1_ip: "192.168.40.44"
gluster_server2_ip: "192.168.40.45"
gluster_server3_ip: "192.168.40.46"
gluster_cluster_size: 2
gluster_root_password: "Welcome1"
